name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hangeoman"
          heroku_email: "wilde.norman@yahoo.com"
          # healthcheck: "https://hangeoman.herokuapp.com/health"
          # checkstring: "ok"
          # rollbackonhealthcheckfailed: true

